Replace proprietary -moz by standard selector
mdn/doc-linter-rules pull request #10
Opened 2017-07-11 08:20 UTC by MatonAnthony

Replace proprietary -moz by standard selector to be compatible with a maximum of browser and with the W3C Standard.

2017-07-11 15:03 UTC, Elchi3 requested changes

2017-07-11 15:03 UTC, Elchi3 commented on lib/pre-without-class.js
> +    let presWithoutClass = rootElement.querySelectorAll(":not([class]), [class='']");
Doesn't this match all elements without class? It should only match `<pre>` elements without class.

2017-07-11 16:13 UTC, MatonAnthony commented on lib/pre-without-class.js
> +    let presWithoutClass = rootElement.querySelectorAll(":not([class]), [class='']");
Looks like I forgot a commit, yes it should only work on <pre>

2017-07-11 16:45 UTC, MatonAnthony commented on lib/pre-without-class.js
> +    let presWithoutClass = rootElement.querySelectorAll(":not([class]), [class='']");
I fixed it and added a test to ensure it doesn't happen again.

2017-07-12 13:01 UTC, Elchi3 approved these changes
Awesome!

2017-07-12 13:01 UTC, merged